[project]
name = "backend"
version = "0.1.0"
description = ""
authors = [
    {name = "Vadim Nevinskiy",email = "vadim_nevinskiy@mail.ru"}
]
requires-python = ">=3.12"
dependencies = [
    "fastapi (>=0.143.0,<0.144.0)",
    "sqlalchemy (>=2.1.4,<3.0.0)",
    "uvicorn (>=0.54.0,<0.55.0)",
    "pydantic-settings (>=2.15.0,<3.0.0)",
    "pydantic[email] (>=2.13.5,<3.0.0)",
    "asyncpg (>=0.32.0,<0.33.0)",
    "psycopg[binary] (>=3.3.6,<4.0.0)",
    "alembic (>=1.20.0,<2.0.0)"
]

[tool.poetry]
package-mode = false

[dependency-groups]
dev = [
    "pytest (>=9.1.1,<10.0.0)",
    "black (>=26.10.0,<27.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
